### ISSUE TITLE
Some UI/UX library ideas

### ISSUE THREAD

**Issue by sedubois** [relatenow/relate#4]
Which one has a good community, is actively developed, and compatible with the relate stack (next.js etc)?

https://ant.design/
https://onsen.io/react
https://github.com/tachyons-css/tachyons
http://react.semantic-ui.com/
https://github.com/reactstrap/reactstrap
http://getuikit.com/

Material Design:
http://www.material-ui.com
https://github.com/mlaursen/react-md
https://www.muicss.com

**Comment by abelovic** [comment]
Have you looked at http://www.material-ui.com?

This is an solid UI framework (based on material design) and has a huge following

**Comment by sedubois** [comment]
Thanks @abelovic 👍 I updated the list and will keep it in mind if/when I get around to the UX part (concentrating on behavior, data, logic etc right now).
